# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Healthcheck < Formula
  desc "A tool for monitoring health status and responsiveness of web applications"
  homepage "https://github.com/marianina8"
  version "1.0.0-beta"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/marianina8/healthcheck/releases/download/1.0.0-beta/healthcheck_Darwin_x86_64.tar.gz"
      sha256 "dc180ea48a0dd9e8633d70b3bc7a96ffa70d89e9f9f65456ccac6df80d26c508"

      def install
        bin.install "healthcheck"
      end
    end
    on_arm do
      url "https://github.com/marianina8/healthcheck/releases/download/1.0.0-beta/healthcheck_Darwin_arm64.tar.gz"
      sha256 "5b3d99ffe9de3e229511d010ccbb251224eb50f55e0443ec8173e69c266e024c"

      def install
        bin.install "healthcheck"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/healthcheck/releases/download/1.0.0-beta/healthcheck_Linux_x86_64.tar.gz"
        sha256 "883a9d3e449e549d86a3551f3ec3584f347ca264660678b5cee9bfb4a5fe9c56"

        def install
          bin.install "healthcheck"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/healthcheck/releases/download/1.0.0-beta/healthcheck_Linux_arm64.tar.gz"
        sha256 "88a03e110cd65092d619c0e9240f4cd399c40d05739f195edd9c0d8f695b241a"

        def install
          bin.install "healthcheck"
        end
      end
    end
  end
end
