# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Healthcheck < Formula
  desc "A tool for monitoring health status and responsiveness of web applications"
  homepage "https://github.com/marianina8"
  version "1.0.1-beta"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/marianina8/healthcheck/releases/download/1.0.1-beta/healthcheck_Darwin_x86_64.tar.gz"
      sha256 "b05d430c985e0fc0e4cde26ec0810e1af8d09a0761008f09ebdfc26e371de39b"

      def install
        bin.install "healthcheck"
      end
    end
    on_arm do
      url "https://github.com/marianina8/healthcheck/releases/download/1.0.1-beta/healthcheck_Darwin_arm64.tar.gz"
      sha256 "b656d966ba44b65f18cbf577db6e83d1d650291b27593b2079c80c8d2741e362"

      def install
        bin.install "healthcheck"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/healthcheck/releases/download/1.0.1-beta/healthcheck_Linux_x86_64.tar.gz"
        sha256 "0266f7ed158b166c1c17c74cf1e0db9a42519286701422c7ff3970f7960be4fc"

        def install
          bin.install "healthcheck"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/healthcheck/releases/download/1.0.1-beta/healthcheck_Linux_arm64.tar.gz"
        sha256 "c0f859d71d4a5afe78c2484c302e7a7895b0caee0b3b31bb1d3858da480931a1"

        def install
          bin.install "healthcheck"
        end
      end
    end
  end
end
